# syntax=docker/dockerfile:1

FROM ruby:3.4.1-slim

# Rails app lives here
WORKDIR /rails

# Install base OS dependencies
RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential \
  curl \
  git \
  libpq-dev \
  nodejs \
  npm \
  postgresql-client && \
  rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install bundler
RUN gem install bundler

# Copy Gemfiles first (dependency caching)
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy package files
COPY package.json package-lock.json ./
RUN npm install

# Bring in the rest of the application
COPY . .

# This will run your Rails dev server + JS & CSS watchers
CMD ["./bin/dev"]